/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author macbook
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBntUsu = new javax.swing.JButton();
        jBntCli = new javax.swing.JButton();
        jBntProd = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBntCC = new javax.swing.JButton();
        jBntCP = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastros = new javax.swing.JMenu();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jMnuFuncionarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuConsulta = new javax.swing.JMenu();
        jMnuCC = new javax.swing.JMenuItem();
        jMnuCF = new javax.swing.JMenuItem();
        jMnuCP = new javax.swing.JMenuItem();
        jMnuCV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBntUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/customer-service_icon-icons.com_51012.png"))); // NOI18N
        jBntUsu.setFocusable(false);
        jBntUsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntUsu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntUsuActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntUsu);

        jBntCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/clients32_1.png"))); // NOI18N
        jBntCli.setFocusable(false);
        jBntCli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntCli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntCliActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntCli);

        jBntProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/carrinho-de-compras1.png"))); // NOI18N
        jBntProd.setFocusable(false);
        jBntProd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntProd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntProdActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntProd);
        jToolBar1.add(jSeparator2);

        jBntCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/clients32_1.png"))); // NOI18N
        jBntCC.setFocusable(false);
        jBntCC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntCC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntCCActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntCC);

        jBntCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/carrinho-de-compras1.png"))); // NOI18N
        jBntCP.setFocusable(false);
        jBntCP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBntCP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBntCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntCPActionPerformed(evt);
            }
        });
        jToolBar1.add(jBntCP);

        jMnuCadastros.setText("Cadastros");

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMnuUsuarios.setMnemonic('u');
        jMnuUsuarios.setText("Usuarios");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuUsuarios);

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMnuClientes.setMnemonic('c');
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuClientes);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto_1.png"))); // NOI18N
        jMnuProdutos.setMnemonic('p');
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuProdutos);

        jMnuFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMnuFuncionarios.setText("Funcionarios");
        jMnuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFuncionariosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuFuncionarios);
        jMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMnuSair.setMnemonic('s');
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuSair);

        jMenuBar1.add(jMnuCadastros);

        jMnuMovimento.setText("Movimentos");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto_1.png"))); // NOI18N
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas);

        jMenuBar1.add(jMnuMovimento);

        jMnuConsulta.setText("Consultas");

        jMnuCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/customers32.png"))); // NOI18N
        jMnuCC.setText("Clientes");
        jMnuCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCCActionPerformed(evt);
            }
        });
        jMnuConsulta.add(jMnuCC);

        jMnuCF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/icons8-grupo-de-usuário-mulher-mulher-30.png"))); // NOI18N
        jMnuCF.setText("Funcionarios");
        jMnuCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCFActionPerformed(evt);
            }
        });
        jMnuConsulta.add(jMnuCF);

        jMnuCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/carrinho-de-compras (1).png"))); // NOI18N
        jMnuCP.setText("Produtos");
        jMnuCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCPActionPerformed(evt);
            }
        });
        jMnuConsulta.add(jMnuCP);

        jMnuCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/etiqueta-de-venda (1).png"))); // NOI18N
        jMnuCV.setText("Vendas");
        jMnuCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCVActionPerformed(evt);
            }
        });
        jMnuConsulta.add(jMnuCV);

        jMenuBar1.add(jMnuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(this, true);
        jDlgUsuarios.setVisible(true);

    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        // TODO add your handling code here:
        JDlgClientes jDlgClientes = new JDlgClientes(null, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        JDlgProduto jDlgProdutos = new JDlgProduto(null, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        // TODO add your handling code here:
        JDlgVendas jDlgVendas = new JDlgVendas(null, true);
        jDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFuncionariosActionPerformed
        // TODO add your handling code here:
        JDlgFuncionarios jDlgFuncionarios = new JDlgFuncionarios(null, true);
        jDlgFuncionarios.setVisible(true);
    }//GEN-LAST:event_jMnuFuncionariosActionPerformed

    private void jMnuCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCCActionPerformed
        // TODO add your handling code here:
        JDlgConsultaClientes JDlgConsultaClientes = new JDlgConsultaClientes(this, true);
        JDlgConsultaClientes.setVisible(true);
    }//GEN-LAST:event_jMnuCCActionPerformed

    private void jMnuCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCFActionPerformed
        // TODO add your handling code here:
        JDlgConsultaFuncionario JDlgConsultaFuncionario = new JDlgConsultaFuncionario(this, true);
        JDlgConsultaFuncionario.setVisible(true);
    }//GEN-LAST:event_jMnuCFActionPerformed

    private void jMnuCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCPActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProdutos JDlgConsultaProdutos = new JDlgConsultaProdutos(this, true);
        JDlgConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuCPActionPerformed

    private void jMnuCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCVActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendas JDlgConsultaVendas = new JDlgConsultaVendas(this, true);
        JDlgConsultaVendas.setVisible(true);
    }//GEN-LAST:event_jMnuCVActionPerformed

    private void jBntUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntUsuActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jBntUsuActionPerformed

    private void jBntCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntCliActionPerformed
        // TODO add your handling code here:
        JDlgClientes jDlgClientes = new JDlgClientes(this, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jBntCliActionPerformed

    private void jBntProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntProdActionPerformed
        // TODO add your handling code here:
        JDlgProduto jDlgProduto = new JDlgProduto(this, true);
        jDlgProduto.setVisible(true);
    }//GEN-LAST:event_jBntProdActionPerformed

    private void jBntCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntCCActionPerformed
        // TODO add your handling code here:
        JDlgConsultaClientes JDlgConsultaClientes = new JDlgConsultaClientes(this, true);
        JDlgConsultaClientes.setVisible(true);
    }//GEN-LAST:event_jBntCCActionPerformed

    private void jBntCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntCPActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProdutos JDlgConsultaProdutos = new JDlgConsultaProdutos(this, true);
        JDlgConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_jBntCPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // (Código opcional para definir o estilo)

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBntCC;
    private javax.swing.JButton jBntCP;
    private javax.swing.JButton jBntCli;
    private javax.swing.JButton jBntProd;
    private javax.swing.JButton jBntUsu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuCC;
    private javax.swing.JMenuItem jMnuCF;
    private javax.swing.JMenuItem jMnuCP;
    private javax.swing.JMenuItem jMnuCV;
    private javax.swing.JMenu jMnuCadastros;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenu jMnuConsulta;
    private javax.swing.JMenuItem jMnuFuncionarios;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
