package bean;
// Generated 25/11/2025 15:50:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgrClientes generated by hbm2java
 */
@Entity
@Table(name="ngr_clientes"
    ,catalog="db_nathalia_reis"
)
public class NgrClientes  implements java.io.Serializable {


     private int ngrIdCliente;
     private String ngrNome;
     private String ngrCpf;
     private String ngrEmail;
     private String ngrTelefone;
     private String ngrEndereco;
     private String ngrCep;
     private Date ngrDataCadastro;
     private String ngrBairro;
     private String ngrCidade;
     private String ngrEstado;
     private Date ngrDataNascimento;
     private String ngrAtivo;
     private int ngrLimiteCredito;
     private String ngrObservacoes;

    public NgrClientes() {
    }

	
    public NgrClientes(int ngrIdCliente) {
        this.ngrIdCliente = ngrIdCliente;
    }
    public NgrClientes(int ngrIdCliente, String ngrNome, String ngrCpf, String ngrEmail, String ngrTelefone, String ngrEndereco, String ngrCep, Date ngrDataCadastro, String ngrBairro, String ngrCidade, String ngrEstado, Date ngrDataNascimento, String ngrAtivo, int ngrLimiteCredito, String ngrObservacoes) {
       this.ngrIdCliente = ngrIdCliente;
       this.ngrNome = ngrNome;
       this.ngrCpf = ngrCpf;
       this.ngrEmail = ngrEmail;
       this.ngrTelefone = ngrTelefone;
       this.ngrEndereco = ngrEndereco;
       this.ngrCep = ngrCep;
       this.ngrDataCadastro = ngrDataCadastro;
       this.ngrBairro = ngrBairro;
       this.ngrCidade = ngrCidade;
       this.ngrEstado = ngrEstado;
       this.ngrDataNascimento = ngrDataNascimento;
       this.ngrAtivo = ngrAtivo;
       this.ngrLimiteCredito = ngrLimiteCredito;
       this.ngrObservacoes = ngrObservacoes;
    }
   
     @Id 

    
    @Column(name="ngr_idCliente", unique=true, nullable=false)
    public int getNgrIdCliente() {
        return this.ngrIdCliente;
    }
    
    public void setNgrIdCliente(int ngrIdCliente) {
        this.ngrIdCliente = ngrIdCliente;
    }

    
    @Column(name="ngr_nome", length=45)
    public String getNgrNome() {
        return this.ngrNome;
    }
    
    public void setNgrNome(String ngrNome) {
        this.ngrNome = ngrNome;
    }

    
    @Column(name="ngr_cpf", length=14)
    public String getNgrCpf() {
        return this.ngrCpf;
    }
    
    public void setNgrCpf(String ngrCpf) {
        this.ngrCpf = ngrCpf;
    }

    
    @Column(name="ngr_email", length=80)
    public String getNgrEmail() {
        return this.ngrEmail;
    }
    
    public void setNgrEmail(String ngrEmail) {
        this.ngrEmail = ngrEmail;
    }

    
    @Column(name="ngr_telefone", length=15)
    public String getNgrTelefone() {
        return this.ngrTelefone;
    }
    
    public void setNgrTelefone(String ngrTelefone) {
        this.ngrTelefone = ngrTelefone;
    }

    
    @Column(name="ngr_endereco", length=100)
    public String getNgrEndereco() {
        return this.ngrEndereco;
    }
    
    public void setNgrEndereco(String ngrEndereco) {
        this.ngrEndereco = ngrEndereco;
    }

    
    @Column(name="ngr_cep", length=9)
    public String getNgrCep() {
        return this.ngrCep;
    }
    
    public void setNgrCep(String ngrCep) {
        this.ngrCep = ngrCep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngr_data_cadastro", length=10)
    public Date getNgrDataCadastro() {
        return this.ngrDataCadastro;
    }
    
    public void setNgrDataCadastro(Date ngrDataCadastro) {
        this.ngrDataCadastro = ngrDataCadastro;
    }

    
    @Column(name="ngr_bairro", length=50)
    public String getNgrBairro() {
        return this.ngrBairro;
    }
    
    public void setNgrBairro(String ngrBairro) {
        this.ngrBairro = ngrBairro;
    }

    
    @Column(name="ngr_cidade", length=50)
    public String getNgrCidade() {
        return this.ngrCidade;
    }
    
    public void setNgrCidade(String ngrCidade) {
        this.ngrCidade = ngrCidade;
    }

    
    @Column(name="ngr_estado", length=2)
    public String getNgrEstado() {
        return this.ngrEstado;
    }
    
    public void setNgrEstado(String ngrEstado) {
        this.ngrEstado = ngrEstado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngr_data_nascimento", length=10)
    public Date getNgrDataNascimento() {
        return this.ngrDataNascimento;
    }
    
    public void setNgrDataNascimento(Date ngrDataNascimento) {
        this.ngrDataNascimento = ngrDataNascimento;
    }

    
    @Column(name="ngr_ativo", length=1)
    public String getNgrAtivo() {
        return this.ngrAtivo;
    }
    
    public void setNgrAtivo(String ngrAtivo) {
        this.ngrAtivo = ngrAtivo;
    }

    
    @Column(name="ngr_limite_credito")
    public int getNgrLimiteCredito() {
        return this.ngrLimiteCredito;
    }
    
    public void setNgrLimiteCredito(int ngrLimiteCredito) {
        this.ngrLimiteCredito = ngrLimiteCredito;
    }

    
    @Column(name="ngr_observacoes", length=45)
    public String getNgrObservacoes() {
        return this.ngrObservacoes;
    }
    
    public void setNgrObservacoes(String ngrObservacoes) {
        this.ngrObservacoes = ngrObservacoes;
    }

    @Override
    public String toString() {
        return this.ngrIdCliente + " - " + this.ngrNome;
    }
    
    @Override
    public boolean equals(Object object) {
        if (object instanceof NgrClientes) {
            NgrClientes clientes = (NgrClientes) object;
            if (clientes.getNgrIdCliente()== this.getNgrIdCliente()) {
                return true;
            }
        }
        return false;
    }

}


