package bean;
// Generated 13/10/2025 15:50:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgrFuncionarios generated by hbm2java
 */
@Entity
@Table(name="ngr_funcionarios"
    ,catalog="db_nathalia_reis"
)
public class NgrFuncionarios  implements java.io.Serializable {


     private int ngrIdFuncionario;
     private String ngrNome;
     private String ngrCpf;
     private String ngrCargo;
     private String ngrTelefone;
     private String ngrEmail;
     private double ngrSalario;
     private Date ngrDataAdmissao;
     private String ngrAtivo;

    public NgrFuncionarios() {
    }

	
    public NgrFuncionarios(int ngrIdFuncionario) {
        this.ngrIdFuncionario = ngrIdFuncionario;
    }
    public NgrFuncionarios(int ngrIdFuncionario, String ngrNome, String ngrCpf, String ngrCargo, String ngrTelefone, String ngrEmail, double ngrSalario, Date ngrDataAdmissao, String ngrAtivo) {
       this.ngrIdFuncionario = ngrIdFuncionario;
       this.ngrNome = ngrNome;
       this.ngrCpf = ngrCpf;
       this.ngrCargo = ngrCargo;
       this.ngrTelefone = ngrTelefone;
       this.ngrEmail = ngrEmail;
       this.ngrSalario = ngrSalario;
       this.ngrDataAdmissao = ngrDataAdmissao;
       this.ngrAtivo = ngrAtivo;
    }
   
     @Id 

    
    @Column(name="ngr_idFuncionario", unique=true, nullable=false)
    public int getNgrIdFuncionario() {
        return this.ngrIdFuncionario;
    }
    
    public void setNgrIdFuncionario(int ngrIdFuncionario) {
        this.ngrIdFuncionario = ngrIdFuncionario;
    }

    
    @Column(name="ngr_nome", length=100)
    public String getNgrNome() {
        return this.ngrNome;
    }
    
    public void setNgrNome(String ngrNome) {
        this.ngrNome = ngrNome;
    }

    
    @Column(name="ngr_cpf", length=14)
    public String getNgrCpf() {
        return this.ngrCpf;
    }
    
    public void setNgrCpf(String ngrCpf) {
        this.ngrCpf = ngrCpf;
    }

    
    @Column(name="ngr_cargo", length=50)
    public String getNgrCargo() {
        return this.ngrCargo;
    }
    
    public void setNgrCargo(String ngrCargo) {
        this.ngrCargo = ngrCargo;
    }

    
    @Column(name="ngr_telefone", length=15)
    public String getNgrTelefone() {
        return this.ngrTelefone;
    }
    
    public void setNgrTelefone(String ngrTelefone) {
        this.ngrTelefone = ngrTelefone;
    }

    
    @Column(name="ngr_email", length=80)
    public String getNgrEmail() {
        return this.ngrEmail;
    }
    
    public void setNgrEmail(String ngrEmail) {
        this.ngrEmail = ngrEmail;
    }

    
    @Column(name="ngr_salario", precision=10)
    public double getNgrSalario() {
        return this.ngrSalario;
    }
    
    public void setNgrSalario(double ngrSalario) {
        this.ngrSalario = ngrSalario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngr_dataAdmissao", length=10)
    public Date getNgrDataAdmissao() {
        return this.ngrDataAdmissao;
    }
    
    public void setNgrDataAdmissao(Date ngrDataAdmissao) {
        this.ngrDataAdmissao = ngrDataAdmissao;
    }

    
    @Column(name="ngr_ativo", length=1)
    public String getNgrAtivo() {
        return this.ngrAtivo;
    }
    
    public void setNgrAtivo(String ngrAtivo) {
        this.ngrAtivo = ngrAtivo;
    }




}


