package bean;
// Generated 25/11/2025 15:50:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgrProdutos generated by hbm2java
 */
@Entity
@Table(name="ngr_produtos"
    ,catalog="db_nathalia_reis"
)
public class NgrProdutos  implements java.io.Serializable {


     private int ngrIdProduto;
     private String ngrNome;
     private String ngrDescricao;
     private String ngrTamanho;
     private String ngrCor;
     private double ngrPreco;
     private String ngrCategoria;
     private Date ngrDataCadastro;

    public NgrProdutos() {
    }

    public NgrProdutos(int ngrIdProduto) {
        this.ngrIdProduto = ngrIdProduto;

    }
	
    public NgrProdutos(int ngrIdProduto, String ngrNome, String ngrDescricao, String ngrTamanho, String ngrCor, double ngrPreco, String ngrCategoria) {
        this.ngrIdProduto = ngrIdProduto;
        this.ngrNome = ngrNome;
        this.ngrDescricao = ngrDescricao;
        this.ngrTamanho = ngrTamanho;
        this.ngrCor = ngrCor;
        this.ngrPreco = ngrPreco;
        this.ngrCategoria = ngrCategoria;
    }
   
   
     @Id 

    
    @Column(name="ngr_idProduto", unique=true, nullable=false)
    public int getNgrIdProduto() {
        return this.ngrIdProduto;
    }
    
    public void setNgrIdProduto(int ngrIdProduto) {
        this.ngrIdProduto = ngrIdProduto;
    }

    
    @Column(name="ngr_nome", nullable=false, length=100)
    public String getNgrNome() {
        return this.ngrNome;
    }
    
    public void setNgrNome(String ngrNome) {
        this.ngrNome = ngrNome;
    }

    
    @Column(name="ngr_descricao", nullable=false)
    public String getNgrDescricao() {
        return this.ngrDescricao;
    }
    
    public void setNgrDescricao(String ngrDescricao) {
        this.ngrDescricao = ngrDescricao;
    }

    
    @Column(name="ngr_tamanho", nullable=false, length=5)
    public String getNgrTamanho() {
        return this.ngrTamanho;
    }
    
    public void setNgrTamanho(String ngrTamanho) {
        this.ngrTamanho = ngrTamanho;
    }

    
    @Column(name="ngr_cor", nullable=false, length=30)
    public String getNgrCor() {
        return this.ngrCor;
    }
    
    public void setNgrCor(String ngrCor) {
        this.ngrCor = ngrCor;
    }

    
    @Column(name="ngr_preco", nullable=false, precision=10)
    public double getNgrPreco() {
        return this.ngrPreco;
    }
    
    public void setNgrPreco(double ngrPreco) {
        this.ngrPreco = ngrPreco;
    }

    
    @Column(name="ngr_categoria", nullable=false, length=50)
    public String getNgrCategoria() {
        return this.ngrCategoria;
    }
    
    public void setNgrCategoria(String ngrCategoria) {
        this.ngrCategoria = ngrCategoria;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngr_dataCadastro", length=10)
    public Date getNgrDataCadastro() {
        return this.ngrDataCadastro;
    }
    
    public void setNgrDataCadastro(Date ngrDataCadastro) {
        this.ngrDataCadastro = ngrDataCadastro;
    }

@Override
    public String toString() {
        return this.ngrIdProduto + " - " + this.ngrNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof NgrProdutos) {
            NgrProdutos produtos = (NgrProdutos) object;
            if (produtos.getNgrIdProduto() == this.getNgrIdProduto()) {
                return true;
            }
        }
        return false;
    }



}


