package bean;
// Generated 25/11/2025 15:50:25 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgrUsuarios generated by hbm2java
 */
@Entity
@Table(name="ngr_usuarios"
    ,catalog="db_nathalia_reis"
)
public class NgrUsuarios  implements java.io.Serializable {


     private int ngrIdUsuarios;
     private String ngrNome;
     private String ngrApelido;
     private String ngrCpf;
     private Date ngrDataNascimento;
     private String ngrSenha;
     private Integer ngrNivel;
     private String ngrAtivo;

    public NgrUsuarios() {
    }

	
    public NgrUsuarios(int ngrIdUsuarios) {
        this.ngrIdUsuarios = ngrIdUsuarios;
    }
    public NgrUsuarios(int ngrIdUsuarios, String ngrNome, String ngrApelido, String ngrCpf, Date ngrDataNascimento, String ngrSenha, Integer ngrNivel, String ngrAtivo) {
       this.ngrIdUsuarios = ngrIdUsuarios;
       this.ngrNome = ngrNome;
       this.ngrApelido = ngrApelido;
       this.ngrCpf = ngrCpf;
       this.ngrDataNascimento = ngrDataNascimento;
       this.ngrSenha = ngrSenha;
       this.ngrNivel = ngrNivel;
       this.ngrAtivo = ngrAtivo;
    }
   
     @Id 

    
    @Column(name="ngr_idUsuarios", unique=true, nullable=false)
    public int getNgrIdUsuarios() {
        return this.ngrIdUsuarios;
    }
    
    public void setNgrIdUsuarios(int ngrIdUsuarios) {
        this.ngrIdUsuarios = ngrIdUsuarios;
    }

    
    @Column(name="ngr_nome", length=50)
    public String getNgrNome() {
        return this.ngrNome;
    }
    
    public void setNgrNome(String ngrNome) {
        this.ngrNome = ngrNome;
    }

    
    @Column(name="ngr_apelido", length=20)
    public String getNgrApelido() {
        return this.ngrApelido;
    }
    
    public void setNgrApelido(String ngrApelido) {
        this.ngrApelido = ngrApelido;
    }

    
    @Column(name="ngr_cpf", length=15)
    public String getNgrCpf() {
        return this.ngrCpf;
    }
    
    public void setNgrCpf(String ngrCpf) {
        this.ngrCpf = ngrCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngr_dataNascimento", length=10)
    public Date getNgrDataNascimento() {
        return this.ngrDataNascimento;
    }
    
    public void setNgrDataNascimento(Date ngrDataNascimento) {
        this.ngrDataNascimento = ngrDataNascimento;
    }

    
    @Column(name="ngr_senha", length=20)
    public String getNgrSenha() {
        return this.ngrSenha;
    }
    
    public void setNgrSenha(String ngrSenha) {
        this.ngrSenha = ngrSenha;
    }

    
    @Column(name="ngr_nivel")
    public Integer getNgrNivel() {
        return this.ngrNivel;
    }
    
    public void setNgrNivel(Integer ngrNivel) {
        this.ngrNivel = ngrNivel;
    }

    
    @Column(name="ngr_ativo", length=1)
    public String getNgrAtivo() {
        return this.ngrAtivo;
    }
    
    public void setNgrAtivo(String ngrAtivo) {
        this.ngrAtivo = ngrAtivo;
    }




}


