package bean;
// Generated 25/11/2025 15:50:25 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NgrVendaProduto generated by hbm2java
 */
@Entity
@Table(name="ngr_venda_produto"
    ,catalog="db_nathalia_reis"
)
public class NgrVendaProduto  implements java.io.Serializable {


     private int ngrIdVendaProduto;
     private NgrProdutos ngrProdutos;
     private NgrVendas ngrVendas;
     private double ngrPrecoUnitario;
     private int ngrQuantidade;

    public NgrVendaProduto() {
    }

	
    public NgrVendaProduto(int ngrIdVendaProduto) {
        this.ngrIdVendaProduto = ngrIdVendaProduto;
    }
    public NgrVendaProduto(int ngrIdVendaProduto, NgrProdutos ngrProdutos, NgrVendas ngrVendas, double ngrPrecoUnitario, int ngrQuantidade) {
       this.ngrIdVendaProduto = ngrIdVendaProduto;
       this.ngrProdutos = ngrProdutos;
       this.ngrVendas = ngrVendas;
       this.ngrPrecoUnitario = ngrPrecoUnitario;
       this.ngrQuantidade = ngrQuantidade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ngr_idVendaProduto", unique=true, nullable=false)
    public int getNgrIdVendaProduto() {
        return this.ngrIdVendaProduto;
    }
    
    public void setNgrIdVendaProduto(int ngrIdVendaProduto) {
        this.ngrIdVendaProduto = ngrIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ngr_fk_idProduto")
    public NgrProdutos getNgrProdutos() {
        return this.ngrProdutos;
    }
    
    public void setNgrProdutos(NgrProdutos ngrProdutos) {
        this.ngrProdutos = ngrProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ngr_fk_idVenda")
    public NgrVendas getNgrVendas() {
        return this.ngrVendas;
    }
    
    public void setNgrVendas(NgrVendas ngrVendas) {
        this.ngrVendas = ngrVendas;
    }

    
    @Column(name="ngr_precoUnitario", precision=10)
    public double getNgrPrecoUnitario() {
        return this.ngrPrecoUnitario;
    }
    
    public void setNgrPrecoUnitario(double ngrPrecoUnitario) {
        this.ngrPrecoUnitario = ngrPrecoUnitario;
    }

    
    @Column(name="ngr_quantidade")
    public int getNgrQuantidade() {
        return this.ngrQuantidade;
    }
    
    public void setNgrQuantidade(int ngrQuantidade) {
        this.ngrQuantidade = ngrQuantidade;
    }




}


