package bean;
// Generated 25/11/2025 15:50:25 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NgrVendas generated by hbm2java
 */
@Entity
@Table(name="ngr_vendas"
    ,catalog="db_nathalia_reis"
)
public class NgrVendas  implements java.io.Serializable {


     private int ngrIdVenda;
     private Date ngrDataVenda;
     private NgrClientes ngrClientes;
     private NgrFuncionarios ngrFuncionario;
     private double ngrValorTotal;

    public NgrVendas() {
    }

	
    public NgrVendas(int ngrIdVenda) {
        this.ngrIdVenda = ngrIdVenda;
    }
    public NgrVendas(int ngrIdVenda, Date ngrDataVenda, NgrClientes ngrClientes, NgrFuncionarios ngrFuncionario, double ngrValorTotal, Set ngrVendaProdutos) {
       this.ngrIdVenda = ngrIdVenda;
       this.ngrDataVenda = ngrDataVenda;
       this.ngrClientes = ngrClientes;
       this.ngrFuncionario = ngrFuncionario;
       this.ngrValorTotal = ngrValorTotal;
    }
   
     @Id 

    
    @Column(name="ngr_idVenda", unique=true, nullable=false)
    public int getNgrIdVenda() {
        return this.ngrIdVenda;
    }
    
    public void setNgrIdVenda(int ngrIdVenda) {
        this.ngrIdVenda = ngrIdVenda;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ngr_fk_cliente")
    public NgrClientes getNgrClientes() {
        return this.ngrClientes;
    }
    
    public void setNgrClientes(NgrClientes ngrclientes) {
        this.ngrClientes = ngrclientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ngr_fk_funcionario")
    public NgrFuncionarios getNgrFuncionarios() {
        return this.ngrFuncionario;
    }
    public void setNgrFuncionarios(NgrFuncionarios ngrFuncionarios) {
        this.ngrFuncionario = ngrFuncionarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngr_dataVenda", length=10)
    public Date getNgrDataVenda() {
        return this.ngrDataVenda;
    }
    
    public void setNgrDataVenda(Date ngrDataVenda) {
        this.ngrDataVenda = ngrDataVenda;
    }

    
    @Column(name="ngr_valorTotal", precision=10)
    public double getNgrValorTotal() {
        return this.ngrValorTotal;
    }
    
    public void setNgrValorTotal(double ngrValorTotal) {
        this.ngrValorTotal = ngrValorTotal;
    }





}


